### ISSUE TITLE
I cant see other players

### ISSUE THREAD

**Issue by werty534tm** [BrandenEK/Blasphemous.Multiplayer#15]
Hi,
Ive been trying to play online multiplayer and I and my colleague succesfully connected to the server, but we cant see each other. The player list command isnt working properly eithr. We tried disabling the randomizer and every mod other than the API, the multiplayer and the console, but its still not working. Would you mind giving me a piece of advice if you know how what we are doing wrong?
Thanks a lot.

**Comment by BrandenEK** [comment]
What version of the mods are you using (As they appear on the title screen) ?  Can you confirm that in the server console it said that both of have joined the server ?

**Comment by BrandenEK** [comment]
What do you mean by ```The player list command isnt working properly eithr```
It seems like someone was not actually connected to the server.  Can you verify that in the BlasServer.exe console it says the other people successfully connected ?
