### ISSUE TITLE
 blasserver.exe does not start

### ISSUE THREAD

**Issue by KelTuz** [BrandenEK/Blasphemous.Multiplayer#27]
Can I get more precise instructions on how to extract files and install this mod?

**Comment by KelTuz** [comment]
> Can I get more precise instructions on how to extract files and install this mod?
The Blasserver.exe does not start, without an error.

**Comment by BrandenEK** [comment]
Can you send me the error then?

**Comment by KelTuz** [comment]
there is no error, it just won't start. And I was able to fix it by installing fraemwork 6.0 or 6.1

**Comment by BrandenEK** [comment]
Ah, I see.  Well I am glad it is working now!
