### ISSUE TITLE
Backslash key does not open the console

### ISSUE THREAD

**Issue by eapiova** [BrandenEK/Blasphemous.Multiplayer#28]
I extracted the Blasphemous Client in my game folder but when ingame "Press the 'backslash' key to open the debug console" doesn't do anything. So I don't know where to input the commands

**Comment by BrandenEK** [comment]
Does the mod name and version appear on the title screen?  If not, then the mod was not loaded.  Apparently I did not add installation instructions to the readme, that is my fault.  Follow the instructions here: (https://github.com/BrandenEK/Blasphemous.Modding.Installer?tab=readme-ov-file#blasphemous-mod-installer).  You will also need the Cheat Console mod and all of its dependencies.  Use the mod installer if you are on windows

**Comment by eapiova** [comment]
Thank you very much, now everything is working properly
